import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import InitialPage from "../src/components/InitialPage";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  useEffect(() => {
    let deferredPrompt;

    window.addEventListener("beforeinstallprompt", (e) => {
      // Prevent the mini-infobar from appearing on mobile
      e.preventDefault();
      // Stash the event so it can be triggered later.
      deferredPrompt = e;
      // Update UI notify the user they can install the PWA
      // showInstallPromotion();
      // Optionally, send analytics event that PWA install promo was shown.
      console.log(`'beforeinstallprompt' event was fired.`);
    });
  }, []);
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>ログイン状態を見る画面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon.png"></link>
        <meta name="theme-color" content="#fff" />
      </Head>

      <main className={styles.main}>
        <InitialPage></InitialPage>
      </main>
    </div>
  );
};

export default Home;
